name: Build draft
on:
  push: 
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Combine
        run: |
            make

      - name: ISO
        uses: MatthiasValvekens/pandoc-iso@master
        with:
          md-in: docs/index.md
          docx-out: docs/index.docx

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: docx-draft
          path: docs/index.docx